apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort # This exposes the port so your laptop can access it
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001 # Your app will be accessible on this port
  selector:
    app: web-app